apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: reviews
spec:
  hosts:
  - reviews
  exportTo:
  - back
  - front
  gateways:
  - mesh
  http:
  - route:
    - destination:
        host: reviews
        subset: v2