apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: basic
  namespace: istio-system
spec:
  security:
    controlPlane:
      mtls: true
    dataPlane:
      automtls: true
      mtls: true
  tracing:
    sampling: 10000
    type: Jaeger
  general:
    logging:
      componentLevels:
        default: info
    validationMessages: true
  profiles:
    - default
  proxy:
    logging:
      level: info
  gateways:
    egress:
      enabled: true
      namespace: istio-system
      service: {}
    ingress:
      enabled: true
      namespace: istio-system
      service: {}
    openshiftRoute:
      enabled: true
  addons:
    grafana:
      enabled: true
    jaeger:
      install:
        ingress:
          enabled: true
        storage:
          memory:
            maxTraces: 100000
          type: Memory
      name: jaeger
    kiali:
      enabled: true
      name: kiali
    prometheus:
      enabled: true
  version: v2.5
  telemetry:
    type: Istiod