apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bookinfo
spec:
  hosts:
  - bookinfo-$USER_NAMESPACE.$EXTERNAL_DOMAIN
  - bookinfo-$USER_NAMESPACE.secure.$EXTERNAL_DOMAIN
  gateways:
  - $USER_NAMESPACE-front/$USER_NAMESPACE-ingress-gateway
  exportTo:
    - istio-system
    - $USER_NAMESPACE-front
  http:
  - match:
    - uri:
        exact: /productpage
    - uri:
        prefix: /static
    - uri:
        exact: /login
    - uri:
        exact: /logout
    - uri:
        prefix: /api/v1/products
    route:
    - destination:
        host: productpage
        port:
          number: 9080
        subset: v1