apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: createroutes
  namespace: istio-system
rules:
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manage-host-routes
rules:
- apiGroups:
  - route.openshift.io
  resources:
  - routes/custom-host
  verbs:
  - create
  - update