apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: getingressdomain
  namespace: openshift-ingress-operator
rules:
- apiGroups:
  - operator.openshift.io
  resources:
  - ingresscontrollers
  verbs:
  - get
