apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: getsvcandroute
  namespace: istio-system
rules:
- apiGroups:
  - ""
  resources:
  - services
  - routes.route.openshift.io
  verbs:
  - get