apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: mysql
  namespace: istio-system
spec:
  exportTo:
  - '.'
  endpoints:
  - address: mysql-1.ddbb.svc.cluster.local
    ports:
      tcp: 3306
  - address: mysql-2.ddbb.svc.cluster.local
    ports:
      tcp: 3306
  - address: mysql-3.ddbb.svc.cluster.local
    ports:
      tcp: 3306
  hosts:
  - mysql.istio-system.svc.cluster.local
  location: MESH_EXTERNAL
  ports:
  - name: tcp
    number: 3306
    protocol: TCP
  resolution: DNS