apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews
spec:
  hosts:
  - reviews
  exportTo:
  - $USER_NAMESPACE-back
  - $USER_NAMESPACE-front
  gateways:
  - mesh
  http:
  - route:
    - destination:
        host: reviews
        subset: v3
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ratings
spec:
  hosts:
  - ratings
  exportTo:
  - $USER_NAMESPACE-back
  - $USER_NAMESPACE-front
  gateways:
  - mesh
  http:
  - route:
    - destination:
        host: ratings
        subset: v2-mysql
      timeout: 4
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: details
spec:
  hosts:
  - details
  exportTo:
  - $USER_NAMESPACE-back
  - $USER_NAMESPACE-front
  gateways:
  - mesh
  http:
  - route:
    - destination:
        host: details
        subset: v1
---